from os.path import join, dirname, abspath
Import('context root_dir libs object_files gtest')

def Build():
  conf = Configure(context.Clone())
  conf.CheckLib('pthread')
  env = conf.Finish()
  env.Append(
    LIBS=libs,
    CCFLAGS=["-fno-strict-aliasing"],
    CPPDEFINES=["__STDC_FORMAT_MACROS"])
  env.Append(
      CPPPATH=[join(root_dir, 'test')],
      CCFLAGS=["-Wno-variadic-macros"])
  return env.Program('cctest', [Glob('*.cc'), gtest, object_files])

program = Build()
Return('program')
