Import('context object_files libs')

def Build():
  conf = Configure(context.Clone())
  conf.CheckLib('pthread')
  conf.CheckLib(library='gtest', language='cxx')
  env = conf.Finish()
  env.Append(
    LIBS=libs,
    CCFLAGS=["-fno-strict-aliasing"],
    CPPDEFINES=["__STDC_FORMAT_MACROS"])
  return env.Program('cctest', [Glob('*.cc'), object_files])

program = Build()
Return('program')
