language: cpp
compiler:
    - clang
    - gcc
before_script:
    - sudo apt-get install -y llvm-3.3-dev libdw-dev libbfd-dev
    - cmake -H. -Bout -DCMAKE_BUILD_TYPE=Debug
script: make -C out && ./out/iv/test/iv_unit_tests && ./out/iv/lv5/test/lv5_unit_tests && make -C out sunspider
notifications:
    recipients:
        - utatane.tea@gmail.com
    email:
        on_success: change
        on_failure: always
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/08227c1b059d9d0c5fb8
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
matrix:
  allow_failures:
    - compiler: clang
