language: cpp
compiler:
    - clang
    - gcc-4.8
before_install:
    - tools/travis/before_install
install:
    - tools/travis/install
before_script:
    - cmake -H. -Bdebug -DCMAKE_BUILD_TYPE=Debug
    - cmake -H. -Brelease -DCMAKE_BUILD_TYPE=Release
script:
    - make -C debug
    - make -C release
    - debug/iv/test/iv_unit_tests
    - release/iv/test/iv_unit_tests
    - debug/iv/lv5/test/lv5_unit_tests
    - release/iv/lv5/test/lv5_unit_tests
    - release/iv/test/benchmarks/aero_benchmarks --benchmark_iterations=100
    - make -C release sunspider
    - TZ=GST+8 python release/tools/download-test262-prefix/src/download-test262/tools/packaging/test262.py --tests=release/tools/download-test262-prefix/src/download-test262 --command=release/iv/lv5/lv5 --summary
notifications:
    recipients:
        - utatane.tea@gmail.com
    email:
        on_success: change
        on_failure: always
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/08227c1b059d9d0c5fb8
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
os:
    - linux
    - osx
matrix:
    allow_failures:
        - compiler: clang
