language: cpp
compiler:
    - clang
    - gcc
before_install:
  - sudo apt-get update -y
install:
    - sudo apt-get install -y llvm-3.3-dev libdw-dev libbfd-dev
before_script:
    - cmake -H. -Bdebug -DCMAKE_BUILD_TYPE=Debug
    - cmake -H. -Brelease -DCMAKE_BUILD_TYPE=Release
script:
    - make -C debug
    - make -C release
    - debug/iv/test/iv_unit_tests
    - release/iv/test/iv_unit_tests
    - debug/iv/lv5/test/lv5_unit_tests
    - release/iv/lv5/test/lv5_unit_tests
    - release/iv/test/benchmarks/aero_benchmarks --benchmark_iterations=100
    - make -C release sunspider
notifications:
    recipients:
        - utatane.tea@gmail.com
    email:
        on_success: change
        on_failure: always
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/08227c1b059d9d0c5fb8
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
matrix:
  allow_failures:
    - compiler: clang
