language: cpp
compiler:
    - clang
    - gcc
before_script:
    - sudo apt-get install -y llvm-3.3-dev
    - cmake -H. -Bout -DCMAKE_BUILD_TYPE=Debug
script: make -C out && ./out/iv/test/iv_unit_tests && ./out/iv/lv5/test/lv5_unit_tests && make -C out sunspider
notifications:
    recipients:
        - utatane.tea@gmail.com
    email:
        on_success: change
        on_failure: always
matrix:
  allow_failures:
    - compiler: clang
