import sys
from os.path import join, dirname, abspath
Import('context object_files root_dir')

def Build():
  env = context.Clone()
  env.Append(
      LIBS=['gc', 'boost_thread'],
      CCFLAGS=["-fno-strict-aliasing"],
      )
  return env.Program('lv5',
      [Glob('*.cc'), Glob('*.c'), object_files])

program = Build()
Return('program')
