from os.path import join, dirname, abspath
Import('context root_dir')

def Build():
  env = context.Clone()
  env.Append(
      CPPPATH=[join(root_dir, 'test')],
      CCFLAGS=["-Wno-variadic-macros"])
  return env.StaticLibrary('gtest', 'gtest-all.cc')

program = Build()
Return('program')
