import sys
from xml.etree.ElementTree import ElementTree

HEADER = """
// This file is auto-generated header by tools/generate-currency.py.
// So do not edit this file.
#ifndef IV_I18N_CURRENCY_H_
#define IV_I18N_CURRENCY_H_
#include <iv/detail/array.h>
#include <iv/detail/unordered_map.h>
namespace iv {
namespace core {
namespace i18n {

struct CurrencyData {
  static const int kMaxCurrencyCodeSize = %d;
  const char* name;
  struct CurrencyCode {
    std::size_t size;
    uint16_t data[kMaxCurrencyCodeSize];
  } code;
};

typedef std::array<CurrencyData, %d> CurrencyDataArray;
static const CurrencyDataArray kCurrencyData = { {
%s
} };

class Currency {
 public:
  enum Type {
%s,
    NUM_OF_CURRENCIES
  };

  typedef CurrencyData Data;
  typedef std::unordered_map<std::string, const Data*> CurrencyMap;

  static const Data* Lookup(StringPiece name) {
    const CurrencyMap::const_iterator it = Map().find(name);
    if (it != Map().end()) {
      return it->second;
    }
    return NULL;
  }

  static const Data* Lookup(Type type) {
    assert(type < NUM_OF_CURRENCIES);
    return kCurrencyData.data() + type;
  }

 private:
  static const CurrencyMap& Map() {
    static const CurrencyMap map = InitMap();
    return map;
  }

  static CurrencyMap InitMap() {
    CurrencyMap map;
    for (const Data* it = kCurrencyData.data(),  // NOLINT
         *last = kCurrencyData.data() + kCurrencyData.size();
         it != last; ++it) {
      map.insert(std::make_pair(it->name, it));
    }
    return map;
  }
};

} } }  // namespace iv::core::i18n
#endif  // IV_I18N_CURRENCY_H_
"""

def dump_line_currency(u):
  res = []
  for c in u:
    res.append(hex(ord(c)))
  return "{ %s }" % (', '.join(res))

def main(source):
  xml = None
  with open(source) as c:
    xml = ElementTree(file=c)

  max_len = 0
  currencies = []
  for currency in xml.findall('.//currency'):
    name = currency.get('type')
    elm = currency.find('symbol')
    if elm is not None:
      symbol = unicode(elm.text)
      currencies.append((name, symbol))
      if max_len < len(symbol):
        max_len = len(symbol)

  print (HEADER %
      (
        max_len,
        len(currencies),
        ',  // NOLINT\n'.join([ '  { "' + c[0] + '", { ' + str(len(c[1])) + 'U, ' + dump_line_currency(c[1]) + ' } }' for c in currencies]) + '  // NOLINT',
        ',\n'.join([ '    ' + c[0].upper() for c in currencies])
       )
      ).strip()

if __name__ == '__main__':
  main(sys.argv[1])
