import sys
import os
from os.path import join, dirname, abspath

Import('root_dir context deps')

files = [
]

src_files = [join(root_dir, 'src', x) for x in files ]
object_files = [join(root_dir, 'obj', 'src', os.path.splitext(x)[0]+'.o') for x in files ]

def Build():
  env = context.Clone()
  netlib_dtoa = context.SConscript(
    'src/third_party/netlib_dtoa/SConscript',
    variant_dir=join(root_dir, 'obj', 'third_party', 'netlib_dtoa'),
    duplicate=False,
    exports="context"
  )
  v8_dtoa = context.SConscript(
    'src/third_party/v8-dtoa/SConscript',
    variant_dir=join(root_dir, 'obj', 'third_party', 'v8_dtoa'),
    duplicate=False,
    exports="context"
  )
  object_files.append([netlib_dtoa, v8_dtoa])

program = Build()
Return("object_files program")
